rollout ModuleExample "Module Example" width:160 height:200
(
	label lbl1 "an example of a module," pos:[24,24] width:128 height:19
	label lbl3 "Pivot Shift is included as" pos:[24,40] width:128 height:16
	label lbl4 "a working example" pos:[32,56] width:96 height:16
	label lbl5 "have fun :)" pos:[48,96] width:64 height:16
	hyperLink linktext "pixelscream" pos:[48,110]  color:green hoverColor:red visitedColor:green address:"http://pixelscream.net/"
)
